all:
	gcc -m32 -o calls-x32 calls.c
	gcc -m64 -o calls-x64 calls.c
	gcc -m32 -o conditionals-x32 conditionals.c
	gcc -m64 -o conditionals-x64 conditionals.c
	gcc -m32 -o fib-x32 fib.c
	gcc -m64 -o fib-x64 fib.c
	gcc -m32 -o loops-x32 loops.c
	gcc -m64 -o loops-x64 loops.c
	gcc -m32 -o increments-x32 increments.c
	gcc -m64 -o increments-x64 increments.c


